[build]
  base = "frontend"
  command = "CI=false npm run build || true"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://employee-hr-platform-1.onrender.com"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"